### PR TITLE
[cudadev] Get rid of cub prefix-scan

### PR DESCRIPTION
**Pull request by PointKernel**
From https://github.com/cms-patatrack/cmssw/pull/447.

### CODE REVIEW

**Comment by makortel** [comment]
Could you copy the changes under `cudadev` and leave `cuda` untouched? I'd prefer to keep the latter frozen (for now at least).

**Comment by PointKernel** [comment]
https://github.com/cms-patatrack/cmssw/pull/447/

**Comment by PointKernel** [comment]
Forgot to mention, it's https://github.com/cms-patatrack/cmssw/pull/447 only. I didn't completely remove cub dependency but only replaced cub prefix-scan.

**Comment by makortel** [comment]
Ah, ok, thanks (I corrected the description, should have looked more carefully).

**Comment by PointKernel** [comment]
> Could you copy the changes under `cudadev` and leave `cuda` untouched? I'd prefer to keep the latter frozen (for now at least).

Sure, I can do that.

**Pull request merged**
