### PR TITLE
Monitor the CPU usage of the event loop

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
Ideally this should give a result similar to `top`, but normalised to the number of threads being used.
On the other hand, it may give too much importance the impact of the initialisation part.

@makortel what do you think ?

Maybe we should add a way to "warm up" the program, skipping the first N events ?

**Comment by fwyzard** [comment]
@makortel @markdewing I wasn't able to build with Kokkos; do you want to test the changes before merging this PR, or do you trust it to work the same as for the other backends ?

**Comment by fwyzard** [comment]
Yes, I skipped it because I didn't have a way to test it at the moment.

**Comment by makortel** [comment]
`kokkos` and `kokkostest` build and work fine with this PR.

I would nevertheless propagate the update to `sycltest`. I think the update working in all other cases makes it likely to work for `sycltest` too, and fixing any (possible) compilation errors would be more straightforward than figuring out which infrastructure updates are missing.

**Comment by fwyzard** [comment]
OK, will do.

**Pull request merged**
