### PR TITLE
Update the version of Eigen to include the Patatrack changes

### PR DESCRIPTION
**Pull request by fwyzard**
This PR updated the version of Eigen to include the changes originally developed by the Patatrack team, please some fixes added by Eric.

### CODE REVIEW

**Comment by makortel** [comment]
Could you describe the expected benefit compared to the previous version of Eigen?

**Comment by fwyzard** [comment]
It should just silence *a lot* of warnings.

**Comment by makortel** [comment]
Sounds good.

**Comment by ericcano** [comment]
The previous version missed many `__device__` function attibutes (in the form or `EIGEN_DEVICE_FUNC` macros), which led to many warnings during compilation. 
But on top, there is a bug in `nvcc`, where it just emits warnings (instead of failing), but also fails to generate the kernel code.

**Comment by ericcano** [comment]
We have a simple reproducer here: https://godbolt.org/z/K5ccocTWW. The second kernel (at the bottom of the PTX output) is just empty.

**Pull request merged**
