### PR TITLE
[alpaka] Split shared objects to backend-specific libraries

### PR DESCRIPTION
**Pull request by fwyzard**
Move common code shared between plugins to a shared library.

### CODE REVIEW

**Comment by fwyzard** [comment]
@makortel we don't expect any impact on the performance from this, do we ?

**Comment by fwyzard** [comment]
However, `alpakatest` does not seem to be working either:
```
$ ./alpakatest --cuda
Found 0 devices.
Processing 1000 events, of which 1 concurrently, with 1 threads.
TestProducer  Event 1 stream 0 ES int 42 FED 1200 size 2152
Floating point exception (core dumped)
```

**Comment by fwyzard** [comment]
OK, that was probably a hardware problem, since just running `nvidia-smi` seems to have crashed the machine :-/

**Comment by makortel** [comment]
> we don't expect any impact on the performance from this, do we ?

In the leading order there should no performance impact. In the sub-leading order shared library reorganization _might_ result in performance differences.

Visually looks good to me.

**Comment by fwyzard** [comment]
OK, now it runs fine, and the perfornance and CPU usage look unchanged:
image
image

**Pull request merged**
